export const AUTH = "AUTH";
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const CHECK_AUTH = "CHECK_AUTH";
export const SET_LOGOUT_TIMER = "SET_LOGOUT_TIMER";
export const CLEAR_AUTH = "CLEAR_AUTH";
export const LOGOUT = "LOGOUT";

export const GET_USERS_INFO = "GET_USERS_INFO";
export const GET_USERS_INFO_START = "GET_USERS_INFO_START"; 
export const GET_USERS_INFO_SUCCESS = "GET_USERS_INFO_SUCCESS";
export const GET_USERS_INFO_FAIL = "GET_USERS_INFO_FAIL";

export const CREATE_TASK = "CREATE_TASK";
export const CREATE_TASK_START = "CREATE_TASK_START";
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const CREATE_TASK_FAIL = "CREATE_TASK_FAIL";

export const GET_MY_TASKS = "GET_MY_TASKS";
export const GET_MY_TASKS_START = "GET_MY_TASKS_START";
export const GET_MY_TASKS_SUCCESS = "GET_MY_TASKS_SUCCESS";
export const GET_MY_TASKS_FAIL = "GET_MY_TASKS_FAIL";

export const GET_TASKS_CREATED = "GET_TASKS_CREATED";
export const GET_TASKS_CREATED_START = "GET_TASKS_CREATED_START";
export const GET_TASKS_CREATED_SUCCESS = "GET_TASKS_CREATED_SUCCESS";
export const GET_TASKS_CREATED_FAIL = "GET_TASKS_CREATED_FAIL";

export const GET_TASK = "GET_TASK";
export const GET_TASK_START = "GET_TASK_START";
export const GET_TASK_SUCCESS = "GET_TASK_SUCCESS";
export const GET_TASK_FAIL = "GET_TASK_FAIL";

export const DELETE_TASK = "DELETE_TASK";
export const DELETE_TASK_START = "DELETE_TASK_START";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_FAIL = "DELETE_TASK_FAIL";

export const DISMISS_AUTH_ERROR = "DISMISS_AUTH_ERROR"; 

export const DISMISS_TASKS_ERROR = "DISMISS_TASKS_ERROR"; 

export const CLEAN_TASKS = "CLEAN_TASKS";